version: '3.9'
services:
  # nextjs:
  #   build:
  #     context: .
  #     dockerfile: "Dockerfiles/web/Dockerfile"
  #   command: npm run dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3000:3000
  mongo:
    build: "./Dockerfiles/mongodb"
    restart: always
    # depends_on:
    #   - nextjs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: instaclone
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27020
    ports:
      - 27020:27020
  adminer:
    image: dockette/adminer:mongo
    restart: always
    ports:
      - 9099:80
