version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27020:27017
  adminer:
    image: dockette/adminer:mongo
    restart: always
    ports:
      - 9099:80
