import SideBar from "@/components/UI/SideBarComponents/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex  ${inter.className} max-h-screen overflow-y-scroll`}
      >
        <SideBar />
        <main className="mx-auto w-[calc(100vw-350px)] ml-[350px]">
          {children}
        </main>
        <div id="modal-hook"></div>
      </body>
    </html>
  );
}
